palette = "catppuccin_mocha"
format = """
$username\
$hostname\
$directory\
$git_state\
$git_status\
$line_break\
$git_branch\
$character"""

[aws]
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"
symbol = "aws "

[azure]
symbol = "az "

[bun]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "bun "

[c]
format = "\\[[$symbol($version(-$name))]($style)\\]"
symbol = "C "

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold purple)"
vimcmd_symbol = "[<](bold green)"

[cmake]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "cmake "

[cmd_duration]
format = "\\[[â± $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "cobol "

[conda]
format = "\\[[$symbol$environment]($style)\\]"
symbol = "conda "

[crystal]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "cr "

[daml]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "daml "

[dart]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "dart "

[deno]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "deno "

[directory]
style = "bold cyan"
read_only = " ro"
truncation_length = 4

[docker_context]
format = "\\[[$symbol$context]($style)\\]"
symbol = "docker "

[dotnet]
format = "\\[[$symbol($version)(ðŸŽ¯ $tfm)]($style)\\]"
symbol = ".NET "

[elixir]
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"
symbol = "exs "

[elm]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "elm "

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[fennel]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "fnl "

[fossil_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "fossil "

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"
symbol = "gcp "

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = ""

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
deleted = "x"
diverged = "<>"
format = "([\\[$all_status$ahead_behind\\]]($style))"
renamed = "r"

[golang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "go "

[gradle]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "gradle "

[guix_shell]
format = "\\[[$symbol]($style)\\]"
symbol = "guix "

[haskell]
format = "\\[[$symbol($version)]($style)\\]"

[haxe]
format = "\\[[$symbol($version)]($style)\\]"

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "hg "

[java]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "java "

[julia]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "jl "

[kotlin]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "kt "

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[lua]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "lua "

[memory_usage]
format = "\\[$symbol[$ram( | $swap)]($style)\\]"
symbol = "memory "

[meson]
format = "\\[[$symbol$project]($style)\\]"
symbol = "meson "

[nim]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "nim "

[nix_shell]
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"
symbol = "nix "

[nodejs]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "nodejs "

[ocaml]
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"
symbol = "ml "

[opa]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "opa "

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[os]
format = "\\[[$symbol]($style)\\]"

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
RedHatEnterprise = "rhel "
Redhat = "rhl "
Redox = "redox "
SUSE = "suse "
Solus = "sol "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "
openEuler = "oeul "
openSUSE = "osuse "

[package]
format = "\\[[$symbol$version]($style)\\]"
symbol = "pkg "

[perl]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "pl "

[php]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "php "

[pijul_channel]
format = "\\[[$symbol$channel]($style)\\]"
symbol = "pijul "

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"
symbol = "pulumi "

[purescript]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "purs "

[python]
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"
symbol = "py "

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"
symbol = "raku "

[red]
format = "\\[[$symbol($version)]($style)\\]"

[ruby]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "rb "

[rust]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "rs "

[scala]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "scala "

[solidity]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "solidity "

[spack]
format = "\\[[$symbol$environment]($style)\\]"
symbol = "spack "

[status]
symbol = "[x](bold red) "

[sudo]
format = "\\[[as $symbol]($style)\\]"
symbol = "sudo "

[swift]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "swift "

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"
symbol = "terraform "

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[zig]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "zig "



[palettes.catppuccin_mocha]
black = "#000000"
red = "#f43841" 
green = "#73c936" 
blue = "#96a6c8" 
yellow = "#ffdd33" 
purple = "#9e95c7" 
cyan = "#c0dbe3" 
white = "#e4e4ef"

